name: Check
on: "push"

jobs:
  check:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - run: make all docs
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

